version: '3.3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: 'movie'
      MYSQL_USER: 'userTest'
      MYSQL_PASSWORD: 'passwordTest'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  api:
    image: api
    container_name: movie-api
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    environment:
      DB_HOST: mysql
      DB_DEV_USER: 'userTest'
      DB_DEV_PASSWORD: 'passwordTest'
      DB_DEV_DATABASE: 'movie'
      DB_TEST_USER: ''
      DB_TEST_PASSWORD: ''
      DB_TEST_DATABASE: ''
      DB_PORT: 3306
      SERVER_PORT: 5000
      NODE_ENV: dev
      WAIT_HOSTS: mysql:3306
    ports: 
    - "5001:5000"
    expose:
      - "5001"
    depends_on:
      - mysql
    command: node server.js