version: '3.3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  api:
    image: api
    container_name: movie-api
    build:
      context: .
      dockerfile: DockerFile
    environment:
      DB_HOST: mysql
      DB_DEV_USER: ''
      DB_DEV_PASSWORD: ''
      DB_DEV_DATABASE: ''
      DB_TEST_USER: ''
      DB_TEST_PASSWORD: ''
      DB_TEST_DATABASE: ''
      DB_PORT: 
      SERVER_PORT: 
      NODE_ENV: dev
    ports: 
    - "5001:5000"
    expose:
      - "5001"